[tool.poetry]
name = "educational_app"
version = "0.1.0"
description = "Образовательное web-приложение для тренировки знаний с использованием LLM Mistral"
authors = ["Mikhail Davydov davydov.mv@phystech.edu"]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
Django = "^4.2"
requests = "^2.28"
mistral = "^1.0"
mistralai = "^1.6.0"
pre-commit = "^4.2.0"
decouple = "^0.0.7"
django-environ = "^0.12.0"
setuptools = "^78.1.0"

[tool.poetry.group.dev.dependencies]
pylint = "^3.3.6"
black = "^23.1"
isort = "^5.12"
pytest = "^7.1"
astroid = "^3.3.9"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pylint]
ignore = ["migrations"]
init-hook = 'import sys; sys.path.append("SparkKnowledge")'
