# Generated by Django 4.2.20 on 2025-04-13 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(max_length=50)),
                ("theme", models.CharField(max_length=100)),
                ("difficulty", models.CharField(max_length=50)),
                (
                    "question_type",
                    models.CharField(
                        help_text="Тип вопроса: множественный выбор, правда/ложь, числовой",
                        max_length=50,
                    ),
                ),
                (
                    "timer",
                    models.PositiveIntegerField(help_text="Время викторины в секундах"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("result_summary", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="QuizDialogue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender",
                    models.CharField(
                        choices=[("user", "Пользователь"), ("model", "Модель")],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dialogues",
                        to="sparkknowledge.quizattempt",
                    ),
                ),
            ],
        ),
    ]
